[
  {
    warehouse_id: 1,
    name_ko: '삼성전자로지텍',
    name_en: 'Samsung Electronics Logitech',
    land_area: null,
    total_ground_area: null,
    common_area: null,
    dedicated_area: 4039,
    completion_date: null,
    address1_ko: '강원도 원주시 문막읍 원문로 2298',
    address1_en: '2298, Wonmun-ro, Munmak-eup, Wonju-si, Gangwon-do',
    address2_ko: null,
    address2_en: null,
    description_ko: null,
    description_en: null,
    note_ko: null,
    note_en: null,
    story: null,
    rent: null,
    category_id: 1,
    restriction_ko: null,
    restriction_en: null,
    access_ko: null,
    access_en: null,
    height: null,
    docking_station: false,
    rack: false,
    is_bonded: null,
    commercial_lift: false,
    is_verified: true,
    createdAt: '2022-02-17T03:04:23.000Z',
    updatedAt: '2022-02-17T04:30:34.000Z',
  },
  {
    warehouse_id: 2,
    name_ko: '삼성전자로지텍㈜',
    name_en: 'Samsung Electronics Logitech Co., Ltd.',
    land_area: null,
    total_ground_area: null,
    common_area: null,
    dedicated_area: 8264.5,
    completion_date: null,
    address1_ko:
      '세종특별자치시 부강면 연청로 745-46, (중부복합물류터미널 5동 배송센터)',
    address1_en:
      '745-46, Yeoncheong-ro, Bugang-myeon, Sejong Special Self-Governing City, (Jungbu Complex Logistics Terminal Building 5 Delivery Center)',
    address2_ko: null,
    address2_en: null,
    description_ko: null,
    description_en: null,
    note_ko: null,
    note_en: null,
    story: null,
    rent: null,
    category_id: 7,
    restriction_ko: null,
    restriction_en: null,
    access_ko: null,
    access_en: null,
    height: null,
    docking_station: null,
    rack: null,
    is_bonded: null,
    commercial_lift: null,
    is_verified: false,
    createdAt: '2022-02-17T03:04:23.000Z',
    updatedAt: '2022-02-17T03:04:23.000Z',
  },
];
